### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by rla** [wouterbeek/plRdf#11]
I see that there are some tests in the test directory. I would like to know how to run them (could be documented in the README).

**Comment by wouterbeek** [comment]
I will turn these into proper plunit tests.
I assume it's standard practice to run these with `swipl test/test.pl`?
It may take me a week or so to get to this task...

**Comment by rla** [comment]
I usually run them with `swipl -s test/test.pl -g run_tests,halt -t 'halt(1)'. This will exit with status 0 when tests succeed and with status 1 when they fail. Good for integrating with other tools.

**Comment by rla** [comment]
I'm looking forward to add Travis support. I have managed to add it to some other packs: <http://rlaanemets.com/post/show/adding-travis-to-swi-prolog-packs>

**Comment by wouterbeek** [comment]
Hi Raivo,

I stumble across this mail now and much confess that I will not be able to
add such tests in the near future after all.  I'm really sorry for
answering the prototypical picture of an academic programmer, but I cannot
find the time at the moment...

If you would be able to add such tests then that would of course be /very/
much appreciated.

I do intend for Semweb/ClioPatria/plRdf to become the most versatile RDF
library in the field, using *LOD Laundromat* as a validation of the
underlying technology stack.  Alas, my current development effort is mostly
directed towards finishing the next LOD Laundromat version.

Btw, I expect Jan to come with revamped literal support in Semweb very
soon.  This will solve most of the problems we were experiencing in Elgin.

---
​Cheers!,
Wouter.

Email: me@wouterbeek.com
WWW: wouterbeek.com
Tel: +31647674624

**Comment by rla** [comment]
I will add some trivial tests. Even just loading a module can test a lot. Trying to do it this week.

**Comment by rla** [comment]
I have looked at possibilities to implement tests in a sane way but cannot currently do it due to imports that use library(something) where something should come from this pack. This requires installation through pack_install and does not allow to test the codebase in the current directory.
